### ISSUE TITLE
Sort Domain list by Name or by Date

### ISSUE THREAD

**Issue by craigcpaterson** [darawish/domainbook#10]
After having imported over 100 domains, I found that it would be a nice addition to be able to sort the listings by domain name or by date.

https://d.pr/i/AgYCwY

**Comment by linuxjuggler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a better table](https://trello.com/c/W5bsYtRH/1-create-a-better-table)

**Comment by linuxjuggler** [comment]
This feature should be in our next release. http://sh.darawish.io/5ede7f
