### ISSUE TITLE
Expired domains show "Expires: date"

### ISSUE THREAD

**Issue by craigcpaterson** [darawish/domainbook#11]
Expired domains should show "Expired: date" and maybe should also be in a different colour, or tinted back to a more subtle grey.

**Comment by linuxjuggler** [comment]
I'll be working on this today to make sure it will be fixed and be part of the next release.

**Comment by craigcpaterson** [comment]
Awesome @linuxjuggler, thank you 👍

**Comment by linuxjuggler** [comment]
Something like this should work 

![Screen_Shot_2019-08-09_at_6_39_24_PM](https://user-images.githubusercontent.com/27624/62791102-27338900-bad5-11e9-8b5e-f98d6e4312e8.jpg)

![Screen_Shot_2019-08-09_at_6_40_35_PM](https://user-images.githubusercontent.com/27624/62791164-4a5e3880-bad5-11e9-8c70-fa51a4b0625d.jpg)

**Comment by linuxjuggler** [comment]
This has been fixed and it will be part of our next version.
