### ISSUE TITLE
Can't import from GoDaddy

### ISSUE THREAD

**Issue by TaoTek** [darawish/domainbook#13]
I just bought DomainBook and I’m very excited to get it going as this is something I really need!

I’m trying to use the **_GoDaddy_** importer.  I got my API key and secret and put them in, but it doesn’t import. It gives me an error message that: “An error occur  an error occur while trying to fetch the records from **name.com**”

I’m not sure why the error message says **name.com** when I’m trying to get the info from **_GoDaddy_**.

Any help would be greatly appreciated as I have a lot of domains in GoDaddy and would  really like to import them.

Thanks!

**Comment by linuxjuggler** [comment]
This has been resolved and will be included within the next release for sure, This [video](http://sh.darawish.io/881cff) explains how it should work.
