### ISSUE TITLE
Add Notes &1 Optional field

### ISSUE THREAD

**Issue by mikelaye** [darawish/domainbook#6]
The app would be useful for us - except we would need 2 further things:

1 - Notes on the domain name (so we could add details of DNS etc)

2 - A field we can use for the client (so we know who it belongs to, as many clients have more than 1 name). Preferably able to sort and filter by this field. This could be optional in Preferences, to keep it simple for those with no need and could be re-named for those attaching names to, say, different projects.

With those 2 additions, this would be an ideal app for us - and I imagine many others like us

**Comment by linuxjuggler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Notes &1 Optional field](https://trello.com/c/KXu31LCJ/6-add-notes-1-optional-field)

**Comment by mikelaye** [comment]
------------------ image-access.net -------------------
   Please note our new number: +44 (0)1172 56 50 50
-------------------------------------------------------

Hi

Thanks for the email. However, when I click the link you sent I'm forwarded to a trello.com URL, for which I don't have a log-in. Please advise.

Best regards

Mike Laye
-------------------------------------------------------
image-access.net
Kings House, 14 Orchard Street, Bristol  BS1 5EH
Phone: +44 (0)1172 56 50 50
-------------------------------------------------------

**Comment by linuxjuggler** [comment]
Hey @mikelaye you can forget about the Trello link its internal one, and it was not supposed to be added, but it was a misconfiguration from my end which caused the link to be added to the issue.

**Comment by linuxjuggler** [comment]
Hey @mikelaye 
I want to let you know that we have started working on this feature

![Screen_Shot_2019-09-11_at_6_00_22_PM](https://user-images.githubusercontent.com/27624/64714290-0e990300-d4c7-11e9-8361-8345c512b2d7.png)

![Screen Shot 2019-09-11 at 7 05 43 PM](https://user-images.githubusercontent.com/27624/64714413-443dec00-d4c7-11e9-9d98-09a09686e9e5.png)

hopefully to release it soon.

Thanks for the feedback.

**Comment by linuxjuggler** [comment]
This one will be part of the next release.

we will try to work on the search/sort functionality for the new fields later
