### ISSUE TITLE
Please add Fasthosts as a registrar

### ISSUE THREAD

**Issue by craigcpaterson** [darawish/domainbook#8]
It would be awesome if you could add [Fasthosts](https://www.fasthosts.co.uk/) as a registrar.

**Comment by linuxjuggler** [comment]
Hey @craigcpaterson we will look into that if they provide an API that we can use we will do our best.

**Comment by linuxjuggler** [comment]
Hey @craigcpaterson I don't think we will add them any soon, based their response via twitter https://twitter.com/FHTechTeam/status/1159824925613613056 the API is only available for the resellers, and to be part of the reseller's program you need to pay about [£19.99/M](https://www.fasthosts.co.uk/reseller-hosting).

I wished this was not the case; in the future, if they open their API for the customers, we will work to add it to the auto-import.

Thanks for understanding.

**Comment by craigcpaterson** [comment]
No problem. I used to be a reseller with Fasthosts, but I only use them for domain registrations now.
I have manually imported all my domains with them now anyway 😉

**Comment by linuxjuggler** [comment]
Sounds great, if there is anything we can do let us know.

Thanks 👍
