### ISSUE TITLE
Add domain information manually

### ISSUE THREAD

**Issue by linuxjuggler** [darawish/domainbook#9]
Due to the EU law, not all registrar provide any public information about the domain, which makes it hard for us to auto add the information.

So manually adding the data (like creation & expiration date) will make it easier for the customers.

**Comment by linuxjuggler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add domain information manually](https://trello.com/c/4heyZPzG/4-add-domain-information-manually)

**Comment by TaoTek** [comment]
I need this too as I have a domain (a .coffee one) that is showing as expired but has actually renewed. When I try to sync it to refresh it says an error occurred trying to refresh the record.

**Comment by linuxjuggler** [comment]
@TaoTek can you send an email to support@darawish with the domain name so we can check from our end.

Also, if you can send us the application logs, at least the most recent one, that would help us. Please check http://sh.darawish.io/87ec24 for how to get access to the logs.

As you can see the logs does not contain any sensitive information, mostly debug messages.

**Comment by linuxjuggler** [comment]
This is going to be part of the new release.
